-- Retired after the super-admin provisioning cutover.
-- Fresh environments must start with zero tenants so production reset deploys
-- cannot accidentally expose a placeholder tenant. Create real tenants through
-- `/super-admin/temples/new` or `npm run provision:temple`.
