-- No-op after the forward identity reset.
-- The clean baseline now uses super_admins, persons, tenant_memberships,
-- role_definitions, and tenant_membership_roles instead of the legacy admin table.
