import { getTranslations } from "next-intl/server";
import type { ExportMeta } from "./types";

/** Shared by every export route — the "Generated by X on Y" / "Page N of M" wrapper text every PDF report shows, regardless of module. */
export async function buildExportMetaLabels(generatedBy: string, generatedAt: Date): Promise<ExportMeta["labels"]> {
  const t = await getTranslations("exportLabels.common");
  const date = generatedAt.toLocaleString("en-IN");
  return {
    generatedByLine: t("generatedBy", { name: generatedBy, date }),
    pageOfLabel: (page: number, total: number) => t("pageOf", { page, total }),
  };
}
