import PDFDocument from "pdfkit";
import type { ColumnDef, ExportMeta } from "./types";

const PAGE_MARGIN = 40;
const ROW_HEIGHT = 20;
const HEADER_BLOCK_HEIGHT = 60;
const COLUMN_HEADER_HEIGHT = 20;

/**
 * pdfkit has no table primitive — this hand-rolls a simple paginated table:
 * a report header (temple name / module / generated-by / date), proportional
 * column widths from ColumnDef.width, a row loop with page-break detection
 * (repeating the column header on each new page), and a final pass over
 * bufferedPageRange() to stamp "Page X of Y" (the total page count isn't
 * known until all content has been drawn).
 */
export function buildPdfBuffer<T>(columns: ColumnDef<T>[], rows: T[], meta: ExportMeta): Promise<Uint8Array> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: PAGE_MARGIN, bufferPages: true, size: "A4", layout: "landscape" });
    const chunks: Buffer[] = [];
    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const pageWidth = doc.page.width - PAGE_MARGIN * 2;
    const totalWeight = columns.reduce((sum, col) => sum + (col.width ?? 20), 0);
    const colWidths = columns.map((col) => ((col.width ?? 20) / totalWeight) * pageWidth);

    function drawReportHeader(): number {
      doc.fontSize(16).font("Helvetica-Bold").fillColor("#000000").text(meta.tenantName, PAGE_MARGIN, PAGE_MARGIN);
      doc.fontSize(12).font("Helvetica").text(meta.title, PAGE_MARGIN, PAGE_MARGIN + 20);
      doc
        .fontSize(9)
        .fillColor("#666666")
        .text(
          `Generated by ${meta.generatedBy} on ${meta.generatedAt.toLocaleString("en-IN")}`,
          PAGE_MARGIN,
          PAGE_MARGIN + 38,
        );
      doc.fillColor("#000000");
      return PAGE_MARGIN + HEADER_BLOCK_HEIGHT;
    }

    function drawColumnHeader(y: number): number {
      let x = PAGE_MARGIN;
      doc.fontSize(9).font("Helvetica-Bold");
      columns.forEach((col, i) => {
        doc.text(col.header, x, y, { width: colWidths[i], ellipsis: true });
        x += colWidths[i];
      });
      doc
        .moveTo(PAGE_MARGIN, y + 14)
        .lineTo(PAGE_MARGIN + pageWidth, y + 14)
        .stroke("#cccccc");
      return y + COLUMN_HEADER_HEIGHT;
    }

    let y = drawColumnHeader(drawReportHeader());
    doc.font("Helvetica").fontSize(8);

    for (const row of rows) {
      if (y + ROW_HEIGHT > doc.page.height - PAGE_MARGIN) {
        doc.addPage();
        y = drawColumnHeader(PAGE_MARGIN);
        doc.font("Helvetica").fontSize(8);
      }
      let x = PAGE_MARGIN;
      columns.forEach((col, i) => {
        const value = col.accessor(row);
        doc.text(value === null ? "—" : String(value), x, y, { width: colWidths[i], ellipsis: true });
        x += colWidths[i];
      });
      y += ROW_HEIGHT;
    }

    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(8)
        .fillColor("#666666")
        .text(`Page ${i - range.start + 1} of ${range.count}`, PAGE_MARGIN, doc.page.height - PAGE_MARGIN + 10, {
          width: pageWidth,
          align: "center",
        });
    }

    doc.end();
  });
}
