/**
 * A generic column definition shared by every export format (xlsx/csv/pdf)
 * and the devotee import template — one accessor per column, no per-format
 * duplication.
 */
export interface ColumnDef<T> {
  key: string;
  header: string;
  /** A real Date/number (not a pre-formatted string) lets xlsx store the cell as an actual date/currency type — see `format` below. */
  accessor: (row: T) => string | number | Date | null;
  /** Column width hint (character units for xlsx, proportional weight for pdf). */
  width?: number;
  /** xlsx-only cell number format applied when the accessor returns a Date/number — "date" needs a Date value, "currency" needs a plain number (rupees, not paise). Ignored for string values, csv, and pdf (which renders its own text representation). */
  format?: "date" | "currency";
}

export interface ExportMeta {
  title: string; // module name, e.g. "Devotees"
  tenantName: string;
  generatedBy: string;
  generatedAt: Date;
  /** Localized wrapper text for the PDF report header/footer — falls back to English when omitted. */
  labels?: {
    /** Pre-rendered replacement for "Generated by {generatedBy} on {date}" — the caller already has generatedBy/generatedAt to interpolate. */
    generatedByLine?: string;
    pageOfLabel?: (page: number, total: number) => string;
  };
}

export type ExportFormat = "xlsx" | "csv" | "pdf";

export interface ExportFile {
  // Uint8Array, not Buffer: exceljs's own .d.ts declares an ambient global
  // `Buffer` shadow (`extends ArrayBuffer`) that merges into and pollutes
  // the real Node Buffer type project-wide once exceljs's types are loaded
  // — Uint8Array is unambiguous and still valid BodyInit for NextResponse.
  buffer: Uint8Array;
  contentType: string;
  filename: string;
}
